export enum RSC {
  PIPELINES_EMPTY_TITLE_TEXT = "pipelines.empty.title.text",
  PIPELINES_EMPTY_DETAIL_MESSAGE = "pipelines.empty.detail.message",
  PIPELINES_CREATE_BUTTON = "pipelines.create.button",
  PIPELINES_LIST_LABEL = "pipelines.list.label",
  PIPELINES_UNKNOWN_MODEL_TEXT = "pipelines.unknownModel.text",
  PIPELINES_STAGE_COUNT_TEXT = "pipelines.stageCount.text",
  PIPELINES_STAGE_TEXT = "pipelines.stage.text",
  PIPELINES_STAGE_META_TEXT = "pipelines.stage.meta.text",
  PIPELINES_CREATE_TITLE_TEXT = "pipelines.create.title.text",
  PIPELINES_CREATING_STATUS = "pipelines.creating.status",
  PIPELINES_CREATE_FAILURE_ALERT = "pipelines.create.failure.alert",
  PIPELINES_PREREQUISITE_ALERT = "pipelines.prerequisite.alert",
  PIPELINES_NAME_LABEL = "pipelines.name.label",
  PIPELINES_MODEL_LABEL = "pipelines.model.label",
  PIPELINES_STAGE_CHAIN_TITLE_TEXT = "pipelines.stageChain.title.text",
  PIPELINES_STAGE_CHAIN_MESSAGE = "pipelines.stageChain.message",
  PIPELINES_STAGE_ADD_BUTTON = "pipelines.stage.add.button",
  PIPELINES_STAGE_NODE_LABEL = "pipelines.stage.node.label",
  PIPELINES_STAGE_START_LABEL = "pipelines.stage.start.label",
  PIPELINES_STAGE_END_LABEL = "pipelines.stage.end.label",
  PIPELINES_STAGE_REMOVE_BUTTON = "pipelines.stage.remove.button",
  PIPELINES_CANCEL_BUTTON = "pipelines.cancel.button"
}
