export enum RSC {
  COMMON_VALUE_UNAVAILABLE_TEXT = "common.value.unavailable.text",
  COMMON_STATUS_REACHABLE_STATUS = "common.status.reachable.status",
  COMMON_STATUS_UNREACHABLE_STATUS = "common.status.unreachable.status",
  COMMON_STATUS_READY_STATUS = "common.status.ready.status",
  COMMON_STATUS_LOADING_STATUS = "common.status.loading.status",
  COMMON_STATUS_ERROR_STATUS = "common.status.error.status",
  COMMON_STATUS_DRAFT_STATUS = "common.status.draft.status",
  COMMON_STATUS_UNKNOWN_STATUS = "common.status.unknown.status",
  COMMON_STATUS_DECLARED_STATUS = "common.status.declared.status",
  COMMON_STATUS_PENDING_STATUS = "common.status.pending.status",
  COMMON_ADAPTER_LLAMACPP_TEXT = "common.adapter.llamacpp.text",
  COMMON_ADAPTER_VLLM_TEXT = "common.adapter.vllm.text",
  COMMON_ADAPTER_SGLANG_TEXT = "common.adapter.sglang.text",
  COMMON_ADAPTER_MOCK_TEXT = "common.adapter.mock.text",
  COMMON_UNIT_GIB_TEXT = "common.unit.gib.text",
  COMMON_UNIT_MILLISECOND_TEXT = "common.unit.millisecond.text",
  COMMON_UNIT_PERCENT_TEXT = "common.unit.percent.text",
  COMMON_UNIT_CELSIUS_TEXT = "common.unit.celsius.text",
  COMMON_UNIT_WATT_TEXT = "common.unit.watt.text"
}
