import { Box, Button, Paper, Typography } from "@mui/material";
import type { StudioSnapshot } from "../../../common/domain.js";
import { formatMessage } from "../../i18n/format.js";
import { useTranslation } from "../../i18n/useTranslation.js";
import { EmptyState } from "../../shared/components/EmptyState.js";
import { Icon } from "../../shared/components/Icon.js";
import { StatusPill } from "../../shared/components/StatusPill.js";
import { RSC } from "./resource.js";

const Metric = ({ label, value, detail, icon }: { label: string; value: number; detail: string; icon: React.ReactNode }) => <Paper variant="outlined" sx={{ p: 2.25, bgcolor: "background.paper", minHeight: 132 }}><Box sx={{ display: "flex", justifyContent: "space-between", color: "text.secondary" }}><Typography variant="body2">{label}</Typography>{icon}</Box><Typography className="metric-number" sx={{ fontSize: 30, fontWeight: 560, mt: 1.5 }}>{String(value).padStart(2, "0")}</Typography><Typography variant="caption" color="text.secondary">{detail}</Typography></Paper>;

export const DashboardView = ({ snapshot, onRegister }: { snapshot: StudioSnapshot; onRegister: () => void }) => {
  const { t } = useTranslation();
  const reachable = snapshot.agents.filter((agent) => agent.reachability === "reachable").length;
  const pipeline = snapshot.pipelines[0];
  return <Box><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr 1fr", lg: "repeat(4, 1fr)" }, gap: 1.5 }}>
    <Metric label={t[RSC.DASHBOARD_METRIC_AGENTS_TEXT]} value={snapshot.agents.length} detail={formatMessage(t[RSC.DASHBOARD_METRIC_AGENTS_DETAIL_MESSAGE], { count: reachable })} icon={<Icon name="dns" fontSize="small" />} />
    <Metric label={t[RSC.DASHBOARD_METRIC_NODES_TEXT]} value={snapshot.nodes.length} detail={t[RSC.DASHBOARD_METRIC_NODES_DETAIL_MESSAGE]} icon={<Icon name="bolt" fontSize="small" />} />
    <Metric label={t[RSC.DASHBOARD_METRIC_MODELS_TEXT]} value={snapshot.models.length} detail={t[RSC.DASHBOARD_METRIC_MODELS_DETAIL_MESSAGE]} icon={<Icon name="memory" fontSize="small" />} />
    <Metric label={t[RSC.DASHBOARD_METRIC_PIPELINES_TEXT]} value={snapshot.pipelines.length} detail={formatMessage(t[RSC.DASHBOARD_METRIC_PIPELINES_DETAIL_MESSAGE], { count: snapshot.pipelines.filter((item) => item.status === "ready").length })} icon={<Icon name="pipeline" fontSize="small" />} />
  </Box><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", xl: "1.45fr .75fr" }, gap: 1.5, mt: 1.5 }}>
    <Paper component="section" aria-labelledby="pipeline-overview-title" variant="outlined" sx={{ p: 2.5, bgcolor: "background.paper", minHeight: 330 }}><Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", mb: 3 }}><Box><Typography id="pipeline-overview-title" variant="h2">{t[RSC.DASHBOARD_TOPOLOGY_TITLE_TEXT]}</Typography><Typography variant="caption" color="text.secondary">{t[RSC.DASHBOARD_TOPOLOGY_DETAIL_MESSAGE]}</Typography></Box>{pipeline && <StatusPill value={pipeline.status} />}</Box>
      {!pipeline ? <EmptyState title={t[RSC.DASHBOARD_TOPOLOGY_EMPTY_TEXT]} detail={t[RSC.DASHBOARD_TOPOLOGY_EMPTY_MESSAGE]} /> : <Box data-testid="pipeline-topology" sx={{ display: "flex", alignItems: "stretch", overflowX: "auto", py: 4 }}>{pipeline.stages.map((stage, index) => { const node = snapshot.nodes.find((item) => item.id === stage.nodeId); const agent = snapshot.agents.find((item) => item.id === node?.agentId); return <Box key={stage.id} sx={{ display: "flex", alignItems: "center" }}><Box data-testid="pipeline-stage" sx={{ width: 190, p: 2, border: "1px solid", borderColor: "divider", bgcolor: "action.hover", borderRadius: 2 }}><Typography variant="caption" color="text.secondary">{formatMessage(t[RSC.DASHBOARD_TOPOLOGY_STAGE_TEXT], { index: index + 1 })}</Typography><Typography sx={{ mt: .8, fontWeight: 600 }}>{node?.name ?? t[RSC.DASHBOARD_TOPOLOGY_UNKNOWN_NODE_TEXT]}</Typography><Typography variant="body2" color="text.secondary">{agent?.name ?? t[RSC.DASHBOARD_TOPOLOGY_NO_AGENT_TEXT]}</Typography><Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 2 }}>{formatMessage(t[RSC.DASHBOARD_TOPOLOGY_LAYERS_TEXT], { start: stage.layerStart, end: stage.layerEnd })}</Typography></Box>{index < pipeline.stages.length - 1 && <Icon className="directional-icon" name="arrow" sx={{ color: "text.disabled", mx: 1.25 }} />}</Box>; })}</Box>}
    </Paper>
    <Paper component="section" aria-labelledby="fleet-status-title" variant="outlined" sx={{ p: 2.5, bgcolor: "background.paper" }}><Typography id="fleet-status-title" variant="h2">{t[RSC.DASHBOARD_FLEET_TITLE_TEXT]}</Typography><Typography variant="caption" color="text.secondary">{t[RSC.DASHBOARD_FLEET_DETAIL_MESSAGE]}</Typography><Box component="ul" sx={{ listStyle: "none", p: 0, mt: 2.75, mb: 0 }}>{snapshot.agents.map((agent) => <Box component="li" key={agent.id} sx={{ py: 1.5, borderTop: "1px solid", borderColor: "divider", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 2 }}><Box><Typography variant="body2" sx={{ fontWeight: 600 }}>{agent.name}</Typography><Typography variant="caption" color="text.secondary">{agent.host}:{agent.port}</Typography></Box><StatusPill value={agent.reachability} /></Box>)}</Box>{snapshot.agents.length === 0 && <Box sx={{ textAlign: "center", py: 6 }}><Typography variant="body2" color="text.secondary">{t[RSC.DASHBOARD_FLEET_EMPTY_MESSAGE]}</Typography><Button size="small" onClick={onRegister} sx={{ mt: 1 }}>{t[RSC.DASHBOARD_FLEET_REGISTER_BUTTON]}</Button></Box>}<Box sx={{ mt: 3, pt: 2, borderTop: "1px solid", borderColor: "divider", display: "flex", justifyContent: "space-between" }}><Typography variant="caption" color="text.secondary">{t[RSC.DASHBOARD_PROTOCOL_LABEL]}</Typography><Typography variant="caption">{formatMessage(t[RSC.DASHBOARD_PROTOCOL_VALUE_TEXT], { frame: snapshot.protocol.frameVersion, event: snapshot.protocol.eventVersion })}</Typography></Box></Paper>
  </Box></Box>;
};
