export enum RSC {
  DASHBOARD_METRIC_NODES_UNKNOWN_TEXT = "dashboard.metric.nodes.unknown.text",
  DASHBOARD_METRIC_AGENTS_TEXT = "dashboard.metric.agents.text",
  DASHBOARD_METRIC_AGENTS_DETAIL_MESSAGE = "dashboard.metric.agents.detail.message",
  DASHBOARD_METRIC_NODES_TEXT = "dashboard.metric.nodes.text",
  DASHBOARD_METRIC_NODES_DETAIL_MESSAGE = "dashboard.metric.nodes.detail.message",
  DASHBOARD_METRIC_MODELS_TEXT = "dashboard.metric.models.text",
  DASHBOARD_METRIC_MODELS_DETAIL_MESSAGE = "dashboard.metric.models.detail.message",
  DASHBOARD_METRIC_PIPELINES_TEXT = "dashboard.metric.pipelines.text",
  DASHBOARD_METRIC_PIPELINES_DETAIL_MESSAGE = "dashboard.metric.pipelines.detail.message",
  DASHBOARD_TOPOLOGY_TITLE_TEXT = "dashboard.topology.title.text",
  DASHBOARD_TOPOLOGY_DETAIL_MESSAGE = "dashboard.topology.detail.message",
  DASHBOARD_TOPOLOGY_EMPTY_TEXT = "dashboard.topology.empty.text",
  DASHBOARD_TOPOLOGY_EMPTY_MESSAGE = "dashboard.topology.empty.message",
  DASHBOARD_TOPOLOGY_STAGE_TEXT = "dashboard.topology.stage.text",
  DASHBOARD_TOPOLOGY_UNKNOWN_NODE_TEXT = "dashboard.topology.unknownNode.text",
  DASHBOARD_TOPOLOGY_NO_AGENT_TEXT = "dashboard.topology.noAgent.text",
  DASHBOARD_TOPOLOGY_LAYERS_TEXT = "dashboard.topology.layers.text",
  DASHBOARD_FLEET_TITLE_TEXT = "dashboard.fleet.title.text",
  DASHBOARD_FLEET_DETAIL_MESSAGE = "dashboard.fleet.detail.message",
  DASHBOARD_FLEET_EMPTY_MESSAGE = "dashboard.fleet.empty.message",
  DASHBOARD_FLEET_REGISTER_BUTTON = "dashboard.fleet.register.button",
  DASHBOARD_PROTOCOL_LABEL = "dashboard.protocol.label",
  DASHBOARD_PROTOCOL_VALUE_TEXT = "dashboard.protocol.value.text"
}
