export enum RSC {
  GROUPS_TITLE_TEXT = "groups.title.text",
  GROUPS_AGENTS_BUTTON = "groups.agents.button",
  GROUPS_PURPOSE_MESSAGE = "groups.purpose.message",
  GROUPS_MISSING_MESSAGE = "groups.missing.message",
  GROUPS_BACK_BUTTON = "groups.back.button",
  GROUPS_FAILURE_ALERT = "groups.failure.alert",
  GROUPS_LOADING_STATUS = "groups.loading.status",
  GROUPS_NAME_LABEL = "groups.name.label",
  GROUPS_MEMBERS_LABEL = "groups.members.label",
  GROUPS_GATEWAY_LABEL = "groups.gateway.label",
  GROUPS_GATEWAY_MESSAGE = "groups.gateway.message",
  GROUPS_SAVE_BUTTON = "groups.save.button",
  GROUPS_CREATE_BUTTON = "groups.create.button",
  GROUPS_EMPTY_MESSAGE = "groups.empty.message",
  GROUPS_EDIT_BUTTON = "groups.edit.button",
  GROUPS_REMOVE_BUTTON = "groups.remove.button",
  GROUPS_REMOVE_MESSAGE = "groups.remove.message",
}
