export enum RSC {
  AGENTS_NODE_OBSERVED_TITLE_TEXT = "agents.node.observed.title.text",
  AGENTS_NODE_ADAPTER_LABEL = "agents.node.adapter.label",
  AGENTS_NODE_GENERATION_LABEL = "agents.node.generation.label",
  AGENTS_NODE_LOAD_GENERATION_LABEL = "agents.node.loadGeneration.label",
  AGENTS_NODE_ADAPTER_STATE_LABEL = "agents.node.adapterState.label",
  AGENTS_NODE_STATE_LABEL = "agents.node.state.label",
  AGENTS_NODE_ADAPTER_BRIEF_MESSAGE = "agents.node.adapterBrief.message",
  AGENTS_NODE_DELIVERY_LABEL = "agents.node.delivery.label",
  AGENTS_NODE_WORKER_STOPPED_LABEL = "agents.node.workerStopped.label",
  AGENTS_NODE_INPUT_RETAINED_LABEL = "agents.node.inputRetained.label",
  AGENTS_NODE_COMPLETION_RETAINED_LABEL = "agents.node.completionRetained.label",
  AGENTS_NODE_LIFECYCLE_RESULT_LABEL = "agents.node.lifecycleResult.label",
  AGENTS_NODE_LOADING_STATUS = "agents.node.loading.status",
  AGENTS_NODE_LOADED_STATUS = "agents.node.loaded.status",
  AGENTS_NODE_UNLOADING_STATUS = "agents.node.unloading.status",
  AGENTS_NODE_FAILED_STATUS = "agents.node.failed.status",
  AGENTS_NODE_UNKNOWN_STATUS = "agents.node.unknown.status",
  AGENTS_NODE_PREVIOUS_OBSERVATION_MESSAGE = "agents.node.previousObservation.message",
  AGENTS_NODE_VALUE_MISSING_TEXT = "agents.node.value.missing.text",
  AGENTS_NODE_VALUE_NULL_TEXT = "agents.node.value.null.text",
  AGENTS_NODE_VALUE_EMPTY_TEXT = "agents.node.value.empty.text",
  AGENTS_NODE_VALUE_TRUE_TEXT = "agents.node.value.true.text",
  AGENTS_NODE_VALUE_FALSE_TEXT = "agents.node.value.false.text",
  AGENTS_NODE_VALUE_ITEMS_TEXT = "agents.node.value.items.text",
}
