import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, TextField } from "@mui/material";
import { useState } from "react";
import { useTranslation } from "../../i18n/useTranslation.js";
import { studioApi } from "../../shared/api/client.js";
import { RSC } from "./resource.js";
import { RSC as COMMON_RSC } from "../../shared/components/resource.js";

export const ModelDialog = ({ open, onClose, onCreated }: { open: boolean; onClose: () => void; onCreated: () => void | Promise<void> }) => {
  const { t } = useTranslation();
  const [name, setName] = useState(""); const [artifact, setArtifact] = useState(""); const [architecture, setArchitecture] = useState(""); const [adapter, setAdapter] = useState("llamacpp"); const [context, setContext] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { await studioApi.createModel({ name, artifact, architecture, adapter, contextLength: context ? Number(context) : null, notes }); setName(""); setArtifact(""); setArchitecture(""); setContext(""); setNotes(""); await onCreated(); } catch { setError(t[RSC.MODELS_REGISTER_FAILURE_ALERT]); } finally { setBusy(false); } };
  return <Dialog open={open} onClose={busy ? undefined : onClose} fullWidth maxWidth="sm" aria-labelledby="model-dialog-title"><form onSubmit={(event) => void submit(event)}><DialogTitle id="model-dialog-title">{t[RSC.MODELS_REGISTER_TITLE_TEXT]}</DialogTitle><DialogContent sx={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 2, pt: "10px !important" }}>{error && <Alert severity="error" role="alert" sx={{ gridColumn: "1 / -1" }}>{error}</Alert>}<TextField label={t[RSC.MODELS_NAME_LABEL]} value={name} onChange={(event) => setName(event.target.value)} required autoFocus sx={{ gridColumn: "1 / -1" }} /><TextField label={t[RSC.MODELS_ARTIFACT_LABEL]} value={artifact} onChange={(event) => setArtifact(event.target.value)} required sx={{ gridColumn: "1 / -1" }} /><TextField label={t[RSC.MODELS_ARCHITECTURE_LABEL]} value={architecture} onChange={(event) => setArchitecture(event.target.value)} required /><TextField select label={t[RSC.MODELS_ADAPTER_LABEL]} value={adapter} onChange={(event) => setAdapter(event.target.value)}><MenuItem value="llamacpp">{t[COMMON_RSC.COMMON_ADAPTER_LLAMACPP_TEXT]}</MenuItem><MenuItem value="vllm">{t[COMMON_RSC.COMMON_ADAPTER_VLLM_TEXT]}</MenuItem><MenuItem value="sglang">{t[COMMON_RSC.COMMON_ADAPTER_SGLANG_TEXT]}</MenuItem></TextField><TextField label={t[RSC.MODELS_CONTEXT_LABEL]} value={context} onChange={(event) => setContext(event.target.value)} type="number" sx={{ gridColumn: "1 / -1" }} /><TextField label={t[RSC.MODELS_NOTES_LABEL]} value={notes} onChange={(event) => setNotes(event.target.value)} multiline minRows={3} sx={{ gridColumn: "1 / -1" }} /></DialogContent><DialogActions sx={{ p: 2.5 }}><Button onClick={onClose} color="secondary">{t[RSC.MODELS_CANCEL_BUTTON]}</Button><Button type="submit" variant="contained" disabled={busy}>{t[busy ? RSC.MODELS_REGISTERING_STATUS : RSC.MODELS_REGISTER_BUTTON]}</Button></DialogActions></form></Dialog>;
};
