export enum RSC {
  MODELS_EMPTY_TITLE_TEXT = "models.empty.title.text",
  MODELS_EMPTY_DETAIL_MESSAGE = "models.empty.detail.message",
  MODELS_REGISTER_BUTTON = "models.register.button",
  MODELS_LIST_LABEL = "models.list.label",
  MODELS_ARTIFACT_TEXT = "models.artifact.text",
  MODELS_CONTEXT_TEXT = "models.context.text",
  MODELS_CONTEXT_VALUE_TEXT = "models.context.value.text",
  MODELS_UNSPECIFIED_TEXT = "models.unspecified.text",
  MODELS_REGISTER_TITLE_TEXT = "models.register.title.text",
  MODELS_REGISTERING_STATUS = "models.registering.status",
  MODELS_REGISTER_FAILURE_ALERT = "models.register.failure.alert",
  MODELS_NAME_LABEL = "models.name.label",
  MODELS_ARTIFACT_LABEL = "models.artifact.label",
  MODELS_ARCHITECTURE_LABEL = "models.architecture.label",
  MODELS_ADAPTER_LABEL = "models.adapter.label",
  MODELS_CONTEXT_LABEL = "models.context.label",
  MODELS_NOTES_LABEL = "models.notes.label",
  MODELS_CANCEL_BUTTON = "models.cancel.button"
}
